### ISSUE TITLE
[Feature Request] Add playbackRate support for playback speed selection like YouTube in the Tizen app

### ISSUE THREAD

**Issue by fredrickthegreat2** [MediaBrowser/SamsungSmartTV#35]
The Tizen framework used for the Emby app in the Samsung Smart TV supports the standard HTML5 video tag `playbackRate` property to increase or decrease the video speed like 1.5x 2x etc. Please enable this feature to be controlled the video menu bar so that we can speed up the videos we are watching. This is very useful if you are listening to academic lectures, long speeches, podcasts etc. One way to implement would be a setting as Youtube does it.

![screen shot 2018-11-26 at 11 27 36 am](https://user-images.githubusercontent.com/45367579/49041534-1df2ce00-f18b-11e8-83d1-f63c3c58bcfd.png)

Tizen docs on playbackRate https://developer.samsung.com/tv/develop/guides/multimedia/media-playback/using-video-elements

![screen shot 2018-11-26 at 2 51 00 pm](https://user-images.githubusercontent.com/45367579/49041540-221eeb80-f18b-11e8-8c37-61576d8152e9.png)

**Comment by fredrickthegreat2** [comment]
This could even be made available for other clients that use HTML component as the `playbackrate` property is pretty standard.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by MarkBarbieri** [comment]
Unfortunately this app is no longer in development.  

For the official app, try requesting in the official Emby forum https://emby.media/community/

**Comment by Heshmatkhah** [comment]
HI @MarkBarbieri 
Can you give me some instructions on how to implement the **Playback Speed Control** feature?
Thank you

**Comment by MarkBarbieri** [comment]
> HI @MarkBarbieri Can you give me some instructions on how to implement the **Playback Speed Control** feature? Thank you

This legacy app is no longer supported as it only works on older (non-Tizen based) TV's prior to 2015.  Please check the forum for details on the official app which is available in most countries app store, or USB Beta installation https://emby.media/community/index.php?/forum/119-samsung-smart-tv/

However, I can tell you that both apps don't use a standard html video element, so playbackRate setting is not available in this form.  The player used does have some support for playback rate, but when enabled only video playback without audio is possible which is not very useful to most people.
