### ISSUE TITLE
Release ZIPs contain .settings and .git directories

### ISSUE THREAD

**Issue by 0ddb0d** [MediaBrowser/SamsungSmartTV#45]
@MarkBarbieri Could you please repack the zips without this junk included as it's tripling the size of the release. TIA.

**Comment by MarkBarbieri** [comment]
Oh, that's interesting.  Looks like the packaging tool isn't smart enough to remove these!  

I'll have to do it tomorrow.  Thanks

**Comment by MarkBarbieri** [comment]
Both releases updated.  Only the .git folder needs to be removed and it can safely done by directly editing the zip file.
