### ISSUE TITLE
Issues playing 4k (specific) video and subtitles sync

### ISSUE THREAD

**Issue by XDavidT** [MediaBrowser/SamsungSmartTV#56]
My Samsung tv model is: UE55TU8000UXSQ
Tizen version is: 1460
I have a lot of issues that different my android/web browser.
Today something happen to the video after few minutes, here is video: https://gofile.io/d/1ae7P3
And also the subtitles (und is the local Hebrew subtitles) showed in other language, not sure why.
Other movies run ok, but subtitles isn't sync right in all the movies..

**Comment by LukePulverenti** [comment]
Hi, please go over a specific example and provide the information requested here that corresponds to that example:
https://emby.media/community/index.php?/topic/790-how-to-report-a-problem/
Thanks.

**Comment by XDavidT** [comment]
As I read, need to open issue in the community, so new one will be open in the forum.
