### ISSUE TITLE
On the "Other IPv6 Sites" tab, there are 4 sites which are consistently returning as bad on the test page, but other test methods seem to work fine. Google chrome account for safari

### ISSUE THREAD

**Issue by Dogscat3831** [MediaBrowser/SamsungSmartTV#61]
On the "Other IPv6 Sites" tab, there are 4 sites which are consistently returning as bad on the test page, but other test methods seem to work fine.

Manually visitng the url `https://ipv6-test-ipv6.eurobilltracker.com/img/1x1.gif?&testdomain=test-ipv6.com&testname=sites` succeeds.
Also, on windows, `ping -6 ipv6-test-ipv6.eurobilltracker.com` succeeds.

The four sites are;
- eurobilltracker.com
- www.limeconsultants.com
- vulndetect.org
- www.duiadns.net

All four exhibit this behavior of commandline pings succeeding and the images loading, but returning a "fail" on the webpage.

__Originally posted by @embermctillhawk in https://github.com/falling-sky/source/issues/198__

**Comment by Dogscat3831** [comment]
> On the "Other IPv6 Sites" tab, there are 4 sites which are consistently returning as bad on the test page, but other test methods seem to work fine.
> 
> 
> 
> Manually visitng the url `https://ipv6-test-ipv6.eurobilltracker.com/img/1x1.gif?&testdomain=test-ipv6.com&testname=sites` succeeds.
> 
> Also, on windows, `ping -6 ipv6-test-ipv6.eurobilltracker.com` succeeds.
> 
> 
> 
> The four sites are;
> 
> - eurobilltracker.com
> 
> - www.limeconsultants.com
> 
> - vulndetect.org
> 
> - www.duiadns.net
> 
> 
> 
> All four exhibit this behavior of commandline pings succeeding and the images loading, but returning a "fail" on the webpage.
> 
> __Originally posted by @embermctillhawk in https://github.com/falling-sky/source/issues/198__

**Comment by LukePulverenti** [comment]
Hi, how does this relate to Emby?

**Comment by embermctillhawk** [comment]
Hi, what the duck is going on here and why am I tagged in this?
