### ISSUE TITLE
__Originally posted by @Dogscat3831 in https://github.com/MediaBrowser/SamsungSmartTV/issues/59

### ISSUE THREAD

**Issue by Dogscat3831** [MediaBrowser/SamsungSmartTV#62]
__Originally posted by @Dogscat3831 in https://github.com/MediaBrowser/SamsungSmartTV/issues/59__

__Originally posted by @Dogscat3831 in https://github.com/MediaBrowser/SamsungSmartTV/issues/60__

**Comment by MarkBarbieri** [comment]
Hi, can you please post these in the Official Emby Forum. https://emby.media/community/index.php?/forum/119-samsung-smart-tv/

This repo is the for the unofficial legacy app (for models before 2016) and is no longer actively supported.

Thanks
